# Generated by Django 2.0.3 on 2018-06-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0002_remove_backlinks_foro'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='GoogleSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Keywords para Google',
            },
        ),
        migrations.AddField(
            model_name='googlebd',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahrefs.GoogleSearch'),
        ),
    ]
