# Generated by Django 2.0.3 on 2018-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0003_auto_20180612_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebd',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
