# Generated by Django 2.0.3 on 2018-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0004_googlebd_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearch',
            name='cant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
