# Generated by Django 2.0.3 on 2018-06-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0005_googlesearch_cant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_bk_single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_from', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url_to', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('Español', 'Español'), ('Ingles', 'Ingles')], max_length=200, null=True)),
                ('anchor', models.CharField(blank=True, max_length=200, null=True)),
                ('nofollow', models.BooleanField()),
                ('site_link', models.CharField(blank=True, choices=[('Comentario', 'Comentario'), ('Articulo', 'Articulo'), ('Foro', 'Foro')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Backlinks del sitio',
            },
        ),
    ]
