# Generated by Django 2.0.3 on 2018-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
