# Generated by Django 2.0.3 on 2018-06-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0008_auto_20180618_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_import',
            name='document',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
