# Generated by Django 2.0.3 on 2018-06-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0009_csv_import_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_import',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
