# Generated by Django 2.0.3 on 2018-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0010_csv_import_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_import',
            name='language',
            field=models.CharField(blank=True, choices=[('Español', 'Español'), ('Ingles', 'Ingles')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='csv_import',
            name='nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csv_import',
            name='site_link',
            field=models.CharField(blank=True, choices=[('Comentario', 'Comentario'), ('Articulo', 'Articulo'), ('Foro', 'Foro')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='csv_import',
            name='url_to',
            field=models.URLField(blank=True, null=True),
        ),
    ]
