# Generated by Django 2.0.3 on 2018-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0011_auto_20180619_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_import',
            name='nofollow',
        ),
    ]
