# Generated by Django 2.0.3 on 2018-06-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0012_remove_csv_import_nofollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
