# Generated by Django 2.0.3 on 2018-06-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0013_scrappertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappertest',
            name='comentario',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scrappertest',
            name='foro',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
