# Generated by Django 2.0.3 on 2018-06-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0015_auto_20180621_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlinks',
            name='foro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='site_link',
            field=models.CharField(blank=True, choices=[('Comentario', 'Comentario'), ('Articulo', 'Articulo')], max_length=200, null=True),
        ),
    ]
