# Generated by Django 2.0.3 on 2018-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0016_auto_20180621_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlinks',
            name='site_link',
            field=models.CharField(blank=True, choices=[('Comentario', 'Comentario'), ('Articulo', 'Articulo'), ('Foro', 'Foro')], max_length=200, null=True),
        ),
    ]
