# Generated by Django 2.0.3 on 2018-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0018_auto_20180621_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleAhref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
