# Generated by Django 2.0.3 on 2018-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0021_tokenahref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_bk_single',
            name='language',
            field=models.CharField(blank=True, choices=[('Español', 'Español'), ('Ingles', 'Ingles'), ('Italiano', 'Italiano'), ('Ruso', 'Ruso'), ('Japones', 'Japones')], max_length=200, null=True),
        ),
    ]
