# Generated by Django 2.0.3 on 2018-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0024_auto_20180712_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_import',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Ingles'), ('it', 'Italiano'), ('ru', 'Ruso'), ('ja', 'Japones')], max_length=200, null=True),
        ),
    ]
