# Generated by Django 2.0.3 on 2018-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0025_auto_20180712_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlinks',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Ingles'), ('it', 'Italiano'), ('ru', 'Ruso'), ('ja', 'Japones'), ('ru', 'Rumano'), ('nl', 'Holandés'), ('ar', 'Armenio'), ('fr', 'Francés'), ('de', 'Aleman'), ('pl', 'Polaco'), ('tw', 'Taiwanes'), ('kr', 'Koreano')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csv_import',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Ingles'), ('it', 'Italiano'), ('ru', 'Ruso'), ('ja', 'Japones'), ('ru', 'Rumano'), ('nl', 'Holandés'), ('ar', 'Armenio'), ('fr', 'Francés'), ('de', 'Aleman'), ('pl', 'Polaco'), ('tw', 'Taiwanes'), ('kr', 'Koreano')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='google_bk_single',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Ingles'), ('it', 'Italiano'), ('ru', 'Ruso'), ('ja', 'Japones'), ('ru', 'Rumano'), ('nl', 'Holandés'), ('ar', 'Armenio'), ('fr', 'Francés'), ('de', 'Aleman'), ('pl', 'Polaco'), ('tw', 'Taiwanes'), ('kr', 'Koreano')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='singlebacklinks',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Ingles'), ('it', 'Italiano'), ('ru', 'Ruso'), ('ja', 'Japones'), ('ru', 'Rumano'), ('nl', 'Holandés'), ('ar', 'Armenio'), ('fr', 'Francés'), ('de', 'Aleman'), ('pl', 'Polaco'), ('tw', 'Taiwanes'), ('kr', 'Koreano')], max_length=200, null=True),
        ),
    ]
