# Generated by Django 2.0.3 on 2018-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0027_auto_20180712_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsearch',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
