# Generated by Django 2.0.3 on 2018-07-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0028_urlsearch_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlinks',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csv_import',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='google_bk_single',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googlebd',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googlesearch',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrappertest',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singleahref',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlebacklinks',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
